# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cc2b1e86-6899-49e1-8192-6715d615625d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/77A8-3961";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

   #4tb
   fileSystems."/home/homelab/drives/4tb" = {
      device = "/dev/disk/by-uuid/a9fc11e5-fd06-4659-b415-25c1022ebefc";
      fsType = "ext4";
      options = [ "nofail" ];
   };

   #8tb
   fileSystems."/home/homelab/drives/8tb" = {
      device = "/dev/disk/by-uuid/b1f3c5b8-f888-4c42-89c5-848b94136e86";
      fsType = "ext4";
      options = [ "nofail" ];
   };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
