$primary = rgb(c1b28b)
$surface = rgb(23211a)
$secondary = rgb(a6b181)
$error = rgb(fd4663)
$tertiary = rgb(90ad85)
$surface_lowest = rgb(11100d)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
