$primary = rgb(d7aa75)
$surface = rgb(231f1a)
$secondary = rgb(c3c76b)
$error = rgb(fd4663)
$tertiary = rgb(95c270)
$surface_lowest = rgb(110f0d)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
