$primary = rgb(67dae4)
$surface = rgb(092a34)
$secondary = rgb(528ce0)
$error = rgb(fd4663)
$tertiary = rgb(5d52e0)
$surface_lowest = rgb(05151a)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
