# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x092a34ff
rootcolor = 0x092a34ff
bordercolor = 0x5f7374ff
dropcolor = 0x67dae480
splitcolor = 0x5d52e0ff
focuscolor = 0x67dae4ff
maximizescreencolor = 0x528ce0ff
urgentcolor = 0xfd4663ff
scratchpadcolor = 0x5d52e0ff
globalcolor = 0x0c838dff
overlaycolor = 0x0a3676ff
jump_label_decorate_fg_color = 0xf2f3f3ff
jump_label_decorate_bg_color = 0x0e3e4eff
jump_label_decorate_focus_fg_color = 0x182425ff
jump_label_decorate_focus_bg_color = 0x67dae4ff
jump_label_decorate_border_color = 0x5f7374ff
