# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x231d1aff
rootcolor = 0x231d1aff
bordercolor = 0x73665fff
dropcolor = 0xd7977580
splitcolor = 0xa5c270ff
focuscolor = 0xd79775ff
maximizescreencolor = 0xc7b96bff
urgentcolor = 0xf3601dff
scratchpadcolor = 0xa5c270ff
globalcolor = 0x7b3f1fff
overlaycolor = 0x62571eff
jump_label_decorate_fg_color = 0xf3f2f2ff
jump_label_decorate_bg_color = 0x362b26ff
jump_label_decorate_focus_fg_color = 0x1f1a19ff
jump_label_decorate_focus_bg_color = 0xd79775ff
jump_label_decorate_border_color = 0x73665fff
group_bar_decorate_fg_color = 0xf3f2f2ff
group_bar_decorate_bg_color = 0x362b26ff
group_bar_decorate_focus_fg_color = 0x1f1a19ff
group_bar_decorate_focus_bg_color = 0xd79775ff
group_bar_decorate_border_color = 0x73665fff
