# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x1a1d23ff
rootcolor = 0x1a1d23ff
bordercolor = 0x616875ff
dropcolor = 0x8b9dc180
splitcolor = 0xa085adff
focuscolor = 0x8b9dc1ff
maximizescreencolor = 0x8981b1ff
urgentcolor = 0xfd4663ff
scratchpadcolor = 0xa085adff
globalcolor = 0x2f436aff
overlaycolor = 0x322c54ff
jump_label_decorate_fg_color = 0xf2f2f3ff
jump_label_decorate_bg_color = 0x272c35ff
jump_label_decorate_focus_fg_color = 0x0e0f12ff
jump_label_decorate_focus_bg_color = 0x8b9dc1ff
jump_label_decorate_border_color = 0x616875ff
